### ISSUE TITLE
setup coverage testing

### ISSUE THREAD

**Issue by guzzijones** [drparadoxical/aeon-rebase#13] opened 2017-12-26 00:46 UTC
Coverity should be setup for unit test coverage.  ** EDIT mistake here meant: - COVERALLS **

**Comment by drparadoxical** [comment] 2017-12-26 01:26
Check the Makefile and objectively determine if that's necessary, or if the test build, coverage, fuzz directives are sufficient for testing and coverage.

**Comment by drparadoxical** [comment] 2017-12-26 03:28
@guzzijones, Coverity appears to be more of a quality/security analysis, and it appears Coveralls is closer to the type of service used to determine unit test coverage (relative to the code itself). 

If I'm not seeing things correctly, by all means point it out, but it appears the following is what we'll need:

1. Buildbot - grades builds and allows for unit/integration/regression/fuzz testing, affording us build status and known test-case coverage (of 100 tests, 80 passed)
2. Coverity - quality/security coverage, which is triggered as an analysis/routine by the builders themselves within Buildbot (I'm assuming this allows for quality/security assessment to be neatly compartmentalized to the builds and unit-tests themselves, though that's still not entirely clear to me)
3. Coveralls - test coverage, also triggered by buildbot builders in CI flow, providing unknown test-case coverage (of 100 tests, you may have passed 100, but be advised only 82% of your code corresponds to these tests, leaving 18% that needs to be deprecated, refactored, outright removed, or have tests built accordingly)

At the very least, I see Buildbot's going to need a place to live and run, so I'll spin up a VPS or VM and make sure it's ready.

The rest, I'll wait to hear back from you and the team, I fear I may be missing some significant aspects of Coverity analysis relative to coverage (again, it seems like more of an audit, less of a coverage).

**Comment by guzzijones** [comment] 2017-12-26 05:00
BuildBot and Coveralls is sufficient.  I was had coverity and coveralls mixed up.

**Comment by guzzijones** [comment] 2017-12-26 05:21
Also I can ping pigeons tomorrow and see what he would charge to spin up buildbot for us.

**Comment by drparadoxical** [comment] 2017-12-26 06:27
Ah, thought so, although I bit the work and we can include Coverity in the mix if need be, but we'll just keep that in our bag of tricks for the time being, and as you said, and as I had already agreed with beforehand, Buildbot and Coveralls does indeed appear to be sufficient. 

@thejourneydude, care to chime in?

**Comment by thejourneydude** [comment] 2017-12-26 17:22
Buildbot and Coveralls works for me. 

Moving forward we should be sure that for every service proposed to be used in this project, we have a clear reason in doing so. Obviously Buildbot and Coveralls makes sense because it saves us time from having to run tests, can give us a general report of potential tests not covered, etc.

**Comment by drparadoxical** [comment] 2017-12-26 18:31
Of the same mind - bottom-up, necessity dictates all, minimalism reigns supreme. 

Once I integrate Coveralls into the CI flow so the Buildbot builders absorb and execute coverage testing, I'll return here with specifics. I'll see if I can't get this bit of devops out of our way today so we can lean on our own semi-formal SOP we've been discussing these past few days. 

We're almost to the center of planning, where systems inherit what optics/logistics have defined, and I'll move over to some new issues to start those discussions now.

**Comment by guzzijones** [comment] 2017-12-26 22:01
Sounds like your setting up buildbot and coveralls. Ok let me know if I need to ping pigeons or i misunderstood.  Thanks!

**Comment by drparadoxical** [comment] 2017-12-26 22:49
You heard correctly. Buildbot and Coveralls on a VM wired up and triggered on commit to run the battery of builds respective to commit. Getting situated in this branch I made earlier, will need to spend time with configurations, and will need to verify closed loops, but once it's done, should be done. 

It's here I saw how we could then move directly and gracefully into development, thus why I'm working towards a functionally correct and complete operating environment alongside a compete-enough SPMP and SRS to discuss and translate into milestones/issues. Talking too damn much about that in another issue, though, so I'll shut the hell up for now.

**Comment by guzzijones** [comment] 2017-12-27 01:00
could you elaborate on what "complete operating environment", "SPMP" ,  and "SRS" mean?  I am not familiar with these terms yet.

**Comment by drparadoxical** [comment] 2017-12-27 01:54
Operating Environment (OE) is a known fancy ass term that's grown over the years to really mean one thing - the general environment in which shit runs, whether it be testing, staging, production. So our Operating Environment here is a VM running Ubuntu 16.04.3 LTS, equipped with Nginx, UFW, Fail2Ban, and of course, Buildbot. We can keep the OE definition roughly this level of specific, as we're not separating builds into a variety of platforms just yet, so we'd be wasting time defining an OE for Android APK build and release until, well...there's actually a damn Android APK build and release cycle. 

Software Project Management Plan (SPMP) refers to IEEE Std. 1058, which evolved into ISO/IEC/IEEE 16326, where 16326 is the standard I recommend when it comes to what we've actually been doing here with these discussions in these issues all along. i.e. SPMP is the strict, formal international standard and guideline for defining a project, how it's managed, how the project management plan itself is managed, infrastructure planning, process modeling, issue assessment and control, QA, fuck shoot me now, this can go on for days. 

Software Requirements Specification (SRS) refers to IEEE Std. 830, a specification I honestly think is one of the most important documents in our shared realms. It provides guidelines for how best to produce software requirements specifications, that's it. 

Instead of getting us bogged down in all that noise, I've been piecing together the specific of the Operating Environment as we've been talking, as well as actively putting those pieces in place and in play, so that our not so strict and not so formal SPMP and can just say "we have this shit set up thusly, over there, shazam and such" and focus more on how best to contain issues into milestones and how precisely that works when it comes to a 1-2 PR combo where we PR here and the PR agaisnt aeonix/aeon-rebase once we're done with the PR review here. 

I've got a subset of the software related IEEE standards over in drparadoxical/aeon-project-planning if you want to take a gander, because honestly, it's not going to tell you anything new, it's just going to put words and structure and priority and precedence and a bit more meaning behind all the things you, again, likely already know. 

I don't want strict, formal approach slowing us down, though, so I'm trying to take the best of both worlds, produce a quick, informal SPMP and SRS relative to the OE set up that stretches from our development instances, to here on Github, to the VM running Buildbot and with Coveralls integrated and as a part of our build/CI flow, such that the things the SPMP will state have been the things we've been actively discussing, topic by topic, and the requirements within the SRS managed by the SPMP are parted out of "rebase the bitch" just enough for us to ensure we can turn them into PR-friendly units of work, because PRs are ultimately how we're going to get work done, get work reviewed, then get work packaged and signed by collaborator as a PR to aeonix/aeon-rebase. 

So all the way to the end of the line, even when it comes to ensuring the collaborators here are recognized for their work on the other side of this damn thing, I've been factoring in, I've kept in mind, and I've just about got this sucker cornered. Thus why I'm pushing on rounding off the OE and closing the CI flow loop so I can hard verify the OE in its entirety is functional and we can all move forward and work against with a certain level of confidence, because after that, we're going straight into aeonix/aeon commit parity push (another issue defines this more thoroughly) and then the meat of the rebase, which is get the thing to walk like a daeuck, talk like a daeuck.

**Comment by drparadoxical** [comment] 2017-12-27 02:07
Here's a good example of horsecockery and why it all ends up being defined within an Operating Environment. 

We have multiple operating environments, integrated environments, integrated development environments, runtime environments, runtime environments on integrated development environments, integrated development environments capable of existing within integrated environments, and now I'm not sure where my sanity went, but I'm positive it's absolutely gone.

**Comment by guzzijones** [comment] 2017-12-27 20:53
I got it.  Thanks for the elaborate explanation. 👍

**Comment by drparadoxical** [comment] 2017-12-30 22:24
This issue was moved to drparadoxical/aeon-rebase-1#5

**Closed by drparadoxical** 2017-12-30 22:24 UTC
